### ISSUE TITLE
Front End Auth 

### ISSUE THREAD

**Issue by bryce2122** [bryce2122/Shapr#2]
- [x]  Styling 

- [x]  login/signup modals 

- [x]  demo 

- [x]  redirect to login if not logged in 

- [x]  logout 

- [x]  redirect to home directory if logged in and visiting a random route

**Comment by xnanodax** [comment]
- [ ] Receiving login errors for demo login
**console messages**
![screen shot 2018-02-06 at 2 30 29 pm](https://user-images.githubusercontent.com/20424731/35887813-5dde1d12-0b4a-11e8-8a5c-d8c22903e806.png)

- [ ] Cannot sign up user
**console messages**
![screen shot 2018-02-06 at 2 31 51 pm](https://user-images.githubusercontent.com/20424731/35887848-80c24a6a-0b4a-11e8-8168-9cfeb637ab98.png)
